export const compliments: Record<string, string> = {
  A: "Adorable 🌸",
  B: "Brilliant ✨",
  C: "Captivating 💕",
  D: "Delightful 🌼",
  E: "Elegant 🌟",
  F: "Fantastic 🎉",
  G: "Gorgeous 🌹",
  H: "Heartwarming 💖",
  I: "Inspiring 🌈",
  J: "Joyful 😍",
  K: "Kindhearted 🤗",
  L: "Lovely 💐",
  M: "Misha loooves you",
  N: "Nurturing 🌱",
  O: "Outstanding 🌞",
  P: "Precious 💎",
  Q: "Queenly 👑",
  R: "Radiant ☀️",
  S: "Sweet 🍯",
  T: "Talented 🎶",
  U: "Unique 🦋",
  V: "Vibrant 🌺",
  W: "Wonderful 🌻",
  X: "Xtraordinary 🌌",
  Y: "Youthful 🌿",
  Z: "Zesty 💫",
};
